# Generated by Django 3.1.7 on 2021-11-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('menu', 'date', 'type')},
        ),
    ]
