# Generated by Django 3.1.7 on 2021-04-22 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meals.menu'),
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('menu', 'date', 'type')},
        ),
        migrations.DeleteModel(
            name='UserMenu',
        ),
    ]
