# Generated by Django 3.1.7 on 2021-03-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20210306_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='diets',
        ),
        migrations.AddField(
            model_name='mealitem',
            name='is_dairy_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
