# Generated by Django 3.1.7 on 2021-04-23 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0002_auto_20210422_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='users',
            field=models.ManyToManyField(related_name='menus', to=settings.AUTH_USER_MODEL),
        ),
    ]
