# Generated by Django 3.1.7 on 2021-03-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20210306_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='is_dairy_free',
            field=models.BooleanField(default=False, help_text='Dairy Free', verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='is_gluten_free',
            field=models.BooleanField(default=False, help_text='Gluten Free', verbose_name='G'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='is_vegetarian',
            field=models.BooleanField(default=False, help_text='Vegetarian', verbose_name='V'),
        ),
    ]
