# Generated by Django 3.1.7 on 2021-04-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_clientmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientmodel',
            unique_together=set(),
        ),
    ]
