# Generated by Django 3.1.7 on 2021-04-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_auto_20210428_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='house_name',
            new_name='name',
        ),
    ]
