# Generated by Django 3.1.7 on 2021-04-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_auto_20210428_0709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientModel',
            new_name='ClientHouse',
        ),
    ]
