# Generated by Django 3.1.7 on 2021-03-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='meal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='diets',
            field=models.JSONField(default=list),
        ),
    ]
